info:
  name: create candidate config
  type: http
  seq: 2

http:
  method: POST
  url: "{{url}}/api/candidate-engine-configs/"
  body:
    type: json
    data: |-
      {
        "source": "fic",
        "is_active": true,
        "mode": "candidate",
        "run_staleness_pass_after_run": true,
        "staleness_sweep_sources": ["fr24", "fpl"]
      }
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false

examples:
  - name: create candidate config
    request:
      url: "{{url}}/api/candidate-engine-configs/"
      method: POST
      body:
        type: json
        data: |-
          {
            "source": "fic",
            "is_active": true,
            "mode": "candidate",
            "run_staleness_pass_after_run": true,
            "staleness_sweep_sources": ["fr24", "fpl"]
          }
    response:
      status: 201
      statusText: Created
      headers:
        - name: server
          value: nginx/1.27.5
        - name: date
          value: Sun, 04 Oct 2026 09:21:12 GMT
        - name: content-type
          value: application/json
        - name: content-length
          value: "293"
        - name: connection
          value: keep-alive
        - name: vary
          value: Accept, origin
        - name: allow
          value: GET, POST, HEAD, OPTIONS
        - name: x-frame-options
          value: DENY, SAMEORIGIN
        - name: x-content-type-options
          value: nosniff, nosniff
        - name: referrer-policy
          value: same-origin, no-referrer-when-downgrade
        - name: cross-origin-opener-policy
          value: same-origin
        - name: x-xss-protection
          value: 1; mode=block
      body:
        type: json
        data: |-
          {
            "status": "success",
            "message": "Candidate Engine Config successfully created",
            "data": {
              "result": {
                "id": 3,
                "source": "fic",
                "is_active": true,
                "mode": "candidate",
                "run_staleness_pass_after_run": true,
                "staleness_sweep_sources": [
                  "fr24",
                  "fpl"
                ],
                "created_at": "2026-10-04T09:21:12.372338Z",
                "updated_at": null
              }
            }
          }
