info:
  name: add system settings
  type: http
  seq: 5

http:
  method: POST
  url: "{{url}}/api/system-settings/"
  body:
    type: json
    data: |-
      {
          "title": "test_settings769",
          "type": "general",
          "value_type": "text",
          "value_text": "fci",
          "bank_details": "fhgewifu"
      }
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: add system settings
    request:
      url: "{{url}}/api/system-settings/"
      method: POST
      body:
        type: json
        data: |-
          {
              "title": "test_settings769",
              "type": "general",
              "value_type": "text",
              "value_text": "fci",
              "bank_details": "fhgewifu"
          }
    response:
      status: 201
      statusText: Created
      headers:
        - name: Date
          value: Tue, 12 Nov 2024 10:20:01 GMT
        - name: Server
          value: WSGIServer/0.2 CPython/3.7.17
        - name: Content-Type
          value: application/json
        - name: Vary
          value: Accept, Origin
        - name: Allow
          value: GET, POST, HEAD, OPTIONS
        - name: X-Frame-Options
          value: DENY
        - name: Content-Length
          value: "329"
        - name: X-Content-Type-Options
          value: nosniff
        - name: Referrer-Policy
          value: same-origin
      body:
        type: json
        data: |-
          {
              "status": "success",
              "message": "System Settings successfully created",
              "data": {
                  "result": {
                      "id": 50,
                      "deleted_at": null,
                      "created_at": "2024-11-12T16:20:01.040553+06:00",
                      "updated_at": null,
                      "title": "test_settings769",
                      "value_text": "fci",
                      "value_file": null,
                      "value_type": "text",
                      "type": "general",
                      "is_active": true,
                      "logo": null,
                      "bank_details": ""
                  }
              }
          }
