"""Builds mkdocs.yml nav from generated pages and overwrites it on every build.

mkdocs.yml is a build artifact, not a hand-maintained file: adding a
new project under collections/ (or a new folder/request inside an
existing one) shows up in the site nav automatically the next time
`occ-docs build` runs, with no manual editing.
"""
from __future__ import annotations

from pathlib import Path

import yaml

from occdocs.generators.base import GeneratedPage

_HEADER = (
    "# THIS FILE IS AUTO-GENERATED by `occ-docs build`. Do not edit by hand --\n"
    "# your changes will be overwritten on the next build. Add or edit content\n"
    "# under collections/ instead.\n"
)


def _page_to_nav(page: GeneratedPage):
    if not page.children:
        return {page.title: str(page.output_path)}
    entries = []
    if page.output_path is not None:
        entries.append({"Overview": str(page.output_path)})
    entries.extend(_page_to_nav(child) for child in page.children)
    return {page.title: entries}


def build_nav(pages: list[GeneratedPage]) -> list:
    return [_page_to_nav(page) for page in pages]


def write_mkdocs_yml(
    output_path: Path,
    site_name: str,
    docs_dir: str,
    nav: list,
    theme: str = "material",
) -> None:
    config = {
        "site_name": site_name,
        "docs_dir": docs_dir,
        "theme": {"name": theme},
        "nav": nav,
    }
    body = yaml.dump(config, sort_keys=False, allow_unicode=True, width=100)
    output_path.write_text(_HEADER + "\n" + body, encoding="utf-8")
